blog/urls.py
from django.urls import path
from .import views

app_name = 'blog'

urlpatterns = [
    path('<id>/post_edit/', views.post_edit, name="post_edit"),
    path('<id>/post_delete/', views.post_delete, name="post_delete"),
    path('<id>/favorite_post/', views.favorite_post, name="favorite_post"),
    path('<id>/<slug>/', views.post_detail, name="post_detail"),
    path('post_create/', views.post_create, name="post_create"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('favorites/', views.post_favorite_list, name="post_favorite_list"),
    path('about/', views.about, name="about"),
    path('contact/', views.Contact, name='contact'),    
]

mysite/urls.py
from django.urls import path, include
from django.contrib import admin
from blog import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as authViews

SOCIAL_AUTH_URL_NAMESPACE = 'social'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.post_list, name="post_list"),
    path('blog/', include('blog.urls')),
    path('login/', views.user_login, name="user_login"),
    path('logout/', views.user_logout, name="user_logout"),
    path('register/', views.register, name="register"),
    path('', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('like/', views.like_post, name="like_post"),     
    #This path will request the customer to type in the email address he or she wants to receive the new instructions to reset the password
    path('password-reset/',
        authViews.PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
        name='password_reset'),
 
    #This will inform the customer a new email has been sent with the instruction
    path('password-reset/done/',
         authViews.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
 
    #This path will provide a specific url with a base64 hash as well as with a token
    path('password-reset-confirm/<uidb64>/<token>/',
        authViews.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),
 
    #This will inform the customer that the password has been changed
    path('password-reset-complete/',
        authViews.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),
        ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status="published")

# Create your models here.
class Post(models.Model):
    objects = models.Manager()      #Our default Manager
    published = PublishedManager()  #Our Custom Model Manager

    STATUS_CHOICES = (
        ('draft','Draft'),
        ('published','Published'),
    )

    title               =       models.CharField(max_length=100)
    slug                =       models.SlugField(max_length=120)
    author              =       models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body                =       models.TextField()
    likes               =       models.ManyToManyField(User, related_name='likes', blank=True)
    created             =       models.DateTimeField(auto_now_add=True)
    updated             =       models.DateTimeField(auto_now=True)
    status              =       models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    restrict_comment    =       models.BooleanField(default=False)
    favorite           =       models.ManyToManyField(User, related_name='favorite', blank=True)



    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()


    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.id, self.slug])

@receiver(pre_save, sender=Post)
def pre_save_slug(sender, **kwargs):
    slug = slugify(kwargs['instance'].title)
    kwargs['instance'].slug = slug


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField(null=True, blank=True)
    photo = models.ImageField(upload_to ='profile/', null=True, blank=True)


    def __str__(self):
        return "Profile of user {}".format(self.user.username)


class Images(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

    class Meta:
        verbose_name = 'images'
        verbose_name_plural = 'images'

    def __str__(self):
        return str(self.post.id)



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.ForeignKey('Comment', null=True, on_delete=models.CASCADE, related_name="replies")
    content = models.TextField(max_length=160)
    timestamp = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return '{}-{}'.format(self.post.title, str(self.user.username))

class Contactus(models.Model):
    name= models.CharField(max_length=200)
    email=models.EmailField(max_length=70)
    message = models.CharField(max_length=300)

    class Meta:
        verbose_name = 'contact us'
        verbose_name_plural = 'contact us'
    
        
    def __str__(self):
        return self.name

blog/views.py
from .models import Post, Profile, Images, Comment, Contactus
from datetime import datetime
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import render_to_string
from django.forms import modelformset_factory
from django.contrib import messages

from django.core.mail import EmailMessage
import requests
from django.conf import settings
from django.template.loader import get_template
# Create your views here.
def about(request):
    return render(request, 'blog/about.html')
    
def post_list(request):
    post_list = Post.published.all()
    query = request.GET.get('q')
    if query:
        post_list = Post.published.filter(
        Q(title__contains = query)|
        Q(author__username = query)|
        Q(body__contains = query)
        )
    paginator = Paginator(post_list, 4)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if page is None:
        start_index = 0
        end_index = 7
    else:
        (start_index, end_index) = proper_pagination(posts, index=4)

    page_range = list(paginator.page_range)[start_index:end_index]

    context = {
        'posts': posts,
        'page_range': page_range,
    }
    return render(request, 'blog/post_list.html', context)

def proper_pagination(posts, index):
    start_index = 0
    end_index = 7
    if posts.number > index:
        start_index = posts.number - index
        end_index = start_index + end_index
    return (start_index, end_index)


def post_detail(request, id, slug):
    post = get_object_or_404(Post, id=id, slug=slug)
    comments = Comment.objects.filter(post=post, reply=None).order_by('-id')
    is_liked = False
    is_favorite = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True

    if post.favorite.filter(id=request.user.id).exists():
        is_favorite = True

    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            content = request.POST.get('content')
            reply_id = request.POST.get('comment_id')
            comment_qs = None
            if reply_id:
                comment_qs = Comment.objects.get(id=reply_id)
            comment = Comment.objects.create(post=post, user=request.user, content=content, reply=comment_qs)
            comment.save()
            # return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form= CommentForm()

    context = {
        'post': post,
        'is_liked': is_liked,
        'is_favorite': is_favorite,
        'total_likes': post.total_likes(),
        'comments': comments,
        'comment_form': comment_form,
    }
    if request.is_ajax():
        html = render_to_string('blog/comments.html', context, request=request)
        return JsonResponse({'form': html})

    return render(request, 'blog/post_detail.html', context)

def post_favorite_list(request):
    user = request.user
    favorite_posts = user.favorite.all()
    context = {
        'favorite_posts': favorite_posts,
    }
    return render(request, 'blog/post_favorite_list.html', context)

def favorite_post(request, id):
    post = get_object_or_404(Post, id=id)
    if post.favorite.filter(id=request.user.id).exists():
        post.favorite.remove(request.user)
    else:
        post.favorite.add(request.user)
    return HttpResponseRedirect(post.get_absolute_url())


def like_post(request):
    # post = get_object_or_404(Post, id=request.POST.get('post_id'))
    post = get_object_or_404(Post, id=request.POST.get('id'))
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else:
        post.likes.add(request.user)
        is_liked = True
    context = {
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
    }
    if request.is_ajax():
        html = render_to_string('blog/like_section.html', context, request=request)
        return JsonResponse({'form': html})



def post_create(request):
    ImageFormset = modelformset_factory(Images, fields=('image',), extra=4)
    if request.method == 'POST':
        form = PostCreateForm(request.POST)
        formset = ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            print(formset.cleaned_data)
            for f in formset:
                print(f.cleaned_data)
                try:
                    photo = Images(post=post, image=f.cleaned_data.get('image'))
                    photo.save()
                except Exception as e:
                    break
            messages.success(request, "Post has been created successfully!")
            return redirect('post_list')
    else:
        form = PostCreateForm()
        formset = ImageFormset(queryset=Images.objects.none())
    context = {
        'form': form,
        'formset': formset,
    }
    return render(request, 'blog/post_create.html', context)

def post_edit(request, id):
    post = get_object_or_404(Post, id=id)
    ImageFormset = modelformset_factory(Images, fields=('image',), extra=4, max_num=4)
    if post.author != request.user:
        raise Http404()
    if request.method == "POST":
        form = PostEditForm(request.POST or None, instance=post)
        formset = ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            form.save()
            print(formset.cleaned_data)
            data = Images.objects.filter(post=post)
            for index, f in enumerate(formset):
                if f.cleaned_data:
                    if f.cleaned_data['id'] is None:
                        photo = Images(post=post, image=f.cleaned_data.get('image'))
                        photo.save()
                    elif f.cleaned_data['image'] is False:
                        photo = Images.objects.get(id=request.POST.get('form-' + str(index) + '-id'))
                        photo.delete()
                    else:
                        photo = Images(post=post, image=f.cleaned_data.get('image'))
                        d = Images.objects.get(id=data[index].id)
                        d.image = photo.image
                        d.save()
            messages.success(request, "{} has been updated successfully!".format(post.title))
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        form = PostEditForm(instance=post)
        formset = ImageFormset(queryset=Images.objects.filter(post=post))
    context = {
    'form': form,
    'post': post,
    'formset': formset,
    }
    return render(request, 'blog/post_edit.html', context)




def post_delete(request, id):
    post = get_object_or_404(Post, id=id)
    if request.user != post.author:
        raise Http404()
    post.delete()
    messages.warning(request, 'post has been deleted successfully!')
    return redirect('post_list')




def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']                        
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('post_list'))
                else:
                    return HttpResponse("User is not active")
            else:
                return HttpResponse("Please Enter A Correct Username And Password. Note That Both Fields May Be Case-Sensitive.")                 
    else:
        form = UserLoginForm()

    context = {
        'form': form,
    }
    return render(request, 'blog/login.html', context)


def user_logout(request):
    logout(request)
    return redirect('post_list')


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            Profile.objects.get_or_create(user=new_user)
            return redirect('user_login')
    else:
        form = UserRegistrationForm()
    context = {
        'form': form,
    }
    return render(request, 'registration/register.html', context)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserEditForm(data=request.POST or None, instance=request.user)
        profile_form = ProfileEditForm(data=request.POST or None, instance=request.user.profile, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            registration = user_form.save()
            registration.set_password(user_form.cleaned_data.get('password'))
            profile_form = ProfileEditForm(request.POST, instance=registration.profile)
            if profile_form.is_valid():
                profile_form.save()
                return redirect('post_list')
                 # return HttpResponseRedirect(reverse("blog:edit_profile"))             
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

templates/blog/about.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Hi! I'm Jimmy</h1>
    <img src="{% static 'blog/jimmysran.png' %}" height=300 />
    <hr>
    <p class="lead">
      Fresh Bachelor's CS Grad, Ex Consultant, & Software Intern, With High Integrity And Interpersonal Skills Searching For Backend Developer Opportunities With A Developing And Driven Team For A Company That Values Transparency, Teamwork, And Personal Growth. Experience Through University Research And Internships Required Me To Work Heavily With AWS And Many Different Types Of Databases On Distributed Networks. I Have Ample Experience In Java, Python, C, Git, RESTful APIs, And SQL Through Countless Of Homework Assignments And Projects. With My Bachelor’s Degree And Internship, I Feel Like I Am Someone Who Can Learn Quickly And Make An Immediate Impact. I Am Very Eager To Prove My Worth And I Believe That I Can Be A Very Perfect Fit For Any Company.
    
    <p>
      <a href="mailto:sjsran@yahoo.com" class="btn btn-primary my-2">Email me</a>
    </div>
  </div>
</section>
{% endblock content %}

templates/blog/alerts.html
<div class="messages">
  {% if messages %}
  {% for message in messages %}
  <p class="alert alert-{{ message.tags }}">
    {{ message }}
  </p>
  {% endfor %}
  {% endif %}
</div>

templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}jimmy's blog{% endblock %}</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
    integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'blog/style.css' %}">
  <script src="https://kit.fontawesome.com/50f24d9052.js" crossorigin="anonymous"></script>
</head>

<body>
  {% include 'blog/navbar.html' %}
  <div class="container my-2">
    {% block content %}
    {% endblock %}
    {% include 'blog/footer.html' %}
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function (event) {
      $('#delete').click(function () {
        return confirm("Are you sure to delete this post?");
      });

      $('.reply-btn').click(function () {
        $(this).parent().parent().next('.replied-comments').fadeToggle()
      });


      $(function () {
        setTimeout(function () {
          $('.alert').slideUp(2000);
        }, 5000);
      });

      $(document).on('click', '#like', function (event) {
        event.preventDefault();
        var pk = $(this).attr('value');
        $.ajax({
          type: 'POST',
          url: '{% url "like_post" %}',
          data: { 'id': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
          dataType: 'json',
          success: function (response) {
            $('#like-section').html(response['form'])
            console.log($('#like-section').html(response['form']));
          },
          error: function (rs, e) {
            console.log(rs.responseText);
          },
        });
      });

      $(document).on('submit', '.comment-form', function (event) {
        event.preventDefault();
        console.log($(this).serialize());
        $.ajax({
          type: 'POST',
          url: $(this).attr('action'),
          data: $(this).serialize(),
          dataType: 'json',
          success: function (response) {
            $('.main-comment-section').html(response['form']);
            $('textarea').val('');
            $('.reply-btn').click(function () {
              $(this).parent().parent().next('.replied-comments').fadeToggle();
              $('textarea').val('');
            });
          },
          error: function (rs, e) {
            console.log(rs.responseText);
          },
        });
      });


      $(document).on('submit', '.reply-form', function (event) {
        event.preventDefault();
        console.log($(this).serialize());
        $.ajax({
          type: 'POST',
          url: $(this).attr('action'),
          data: $(this).serialize(),
          dataType: 'json',
          success: function (response) {
            $('.main-comment-section').html(response['form']);
            $('textarea').val('');
            $('.reply-btn').click(function () {
              $(this).parent().parent().next('.replied-comments').fadeToggle();
              $('textarea').val('');
            });
          },
          error: function (rs, e) {
            console.log(rs.responseText);
          },
        });
      });

















    });
  </script>
</body>

</html>

templates/blog/comments.html
<div class="container-fluid mt-1">
  <div class="form-group row">
    <form method="post" class="comment-form" action=".">
      {% csrf_token %}
      {{ comment_form.as_p }}
      {% if request.user.is_authenticated %}
      <input type="submit" value="Submit" class="btn btn-outline-secondary btn-sm">
      {% else %}
      <input type="submit" value="Submit" class="btn btn-outline-secondary btn-sm" disabled>
      {% endif %}
    </form>
  </div>
</div>

<small class="text-muted">{{ comments.count }} Comment{{ comments|pluralize }}</small>
{% for comment in comments %}
<blockquote class="blockquote">
  <p class="mb-0"><small>{{ comment.content }}</small></p>
  <footer class="blockquote-footer"><small>by <cite title="Source Title">{{ comment.user|capfirst }}</cite></small>
    <button type="button" name="button" class="reply-btn btn btn-outline-dark btn-sm ml-2">Reply</button>
  </footer>
</blockquote>

<div class="replied-comments container mt-2" style="display:none;">
  {% for reply in comment.replies.all %}
  <blockquote class="blockquote">
    <p class="mb-0"><small>{{ reply.content }}</small></p>
    <footer class="blockquote-footer"><small>by <cite title="Source Title">{{ reply.user|capfirst }}</cite></small>
    </footer>
  </blockquote>
  {% endfor %}
  <div class="form-group row">
    <form method="post" class="reply-form" action=".">
      {% csrf_token %}
      <input type="hidden" name="comment_id" value="{{ comment.id }}">
      {{ comment_form.as_p }}
      {% if request.user.is_authenticated %}
      <input type="submit" value="Submit" class="btn btn-outline-secondary">
      {% else %}
      <input type="submit" value="Submit" class="btn btn-outline-secondary" disabled>
      {% endif %}
    </form>
  </div>
</div>
{% endfor %}

templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="content-section">
    <form method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4"> Get in Touch </legend>
            {{ form | crispy }}
            <script src='https://www.google.com/recaptcha/api.js'></script>
            <div class="g-recaptcha" data-sitekey="6LcSs-EUAAAAAHOFl2bdqqASBXOjMFdci3NYD7bG"></div>
        </fieldset>
        <div class="form-group">
            <input type="submit" value="Submit" class="btn btn-outline-success">
        </div>
    </form>

</div>
{% endblock %}

templates/blog/edit_profile.html
{% extends 'blog/base.html' %}
{% block title %}Edit Profile | {{ block.super }}{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
  <form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Profile Info</legend>
      {{ user_form | crispy }}
      {{ profile_form | crispy }}
    </fieldset>
    <div class="form-group">
      <input type="submit" value="Update" class="btn btn-outline-info">
    </div>
  </form>
</div>
{% endblock %}

templates/blog/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">&copy; Jimmy,{% now "Y" %}. All Rights Reserved.</p>
</div>

templates/blog/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light bg-steel">
  <a class="navbar-brand" href="{% url 'post_list' %}">jimmy's Blog <i class="fas fa-home"></i></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse navBarSearchForm" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
      <form class="form-inline my-1 my-sm-0" action="{% url 'post_list' %}">
        <input class="form-control mr-sm-1" type="search" placeholder="Search" aria-label="Search" name='q'>
        <button class="btn btn-secondary btn-sm my-1 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
      </form>
    </ul>
    <ul class="navbar-nav mr-1 nav-item">      
      
{% if request.user.is_authenticated %}
<li class="nav-item dropdown dropdown-item">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
    aria-haspopup="true" aria-expanded="false">
    {% if request.user.profile.photo %}
    <img src="{{ request.user.profile.photo.url }}" alt="" class="navbar-img">
    {% else %}          
    <img src="/media/default-avatar.png" alt="" class="navbar-img">
    {% endif %}
    Welcome, {{ request.user|capfirst }}
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <a class="dropdown-item" href="{% url 'blog:edit_profile' %}">My Profile</a>
    <a class="dropdown-item" href="{% url 'blog:post_create' %}">Post Create</a>
    <a class="dropdown-item" href="{% url 'blog:post_favorite_list' %}">Favorite</a>
    <a class="dropdown-item" href="{% url 'user_logout' %}">Logout <i class="fas fa-sign-out-alt"></i></a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'blog:contact' %}">Contact Us</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'blog:about' %}">About Me</a>
    <a class="dropdown-item" href="https://github.com/SatwinderSran?tab=repositories">My Github</a>
    <a class="dropdown-item" href="https://www.linkedin.com/in/jimmy-sran-5414b7179 ">My Linkedin</a>
  </div>
</li>


      {% else %}
      <li class="navbar-brand">
        <a href="{% url 'user_login' %}" class="nav-link">Login <i class="fas fa-sign-in-alt"></i></a>
      </li>
      {% endif %}
    </ul>

  </div>
</nav>

templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block title %}{{ post.title }} | {{ block.super }}{% endblock %}

{% block content %}
{% include 'blog/alerts.html' %}


<h5>{{ post.title }}</h5>
<small>Post created by: {{ post.author }}</small>
<hr>
<p>{{ post.body }}</p>

<div class="row gallery">
  {% for p in post.images_set.all %}
  {% if p.image %}
  <div class="col-md-3">
    <img src="{{ p.image.url }}" alt="Image Not Found" class="img-thumbnail">
  </div>
  {% endif %}
  {% endfor %}
</div>

<div class="border-top pt-3">
  <small class="text-muted">
    Sign In<a class="ml-2" href="{% url 'user_login' %}">Here</a> to comment,add post in Favorite and to like!
  </small></div>
<hr>
<div id="like-section">
  {% include 'blog/like_section.html' %}
</div>
{% if request.user.is_authenticated %}
<div id="favorite-section">
  {% if is_favorite %}
  <a href="{% url 'blog:favorite_post' id=post.id %}">
    <button class="btn btn-danger btn-sm"><i class="fas fa-heart-broken fa-sm"></i></button>
  </a>
  {% else %}
  <a href="{% url 'blog:favorite_post' id=post.id %}">
    <button class="btn btn-success btn-sm"><i class="far fa-heart fa-sm"></i></button>
  </a>
  {% endif %}

</div>
{% endif %}

{% if post.author == request.user %}

<div class="section-1" style="float:right;">

  <a href="{% url 'blog:post_edit' id=post.id %}">
    <button type="button" class="btn btn-outline-secondary">Edit <i class="fas fa-edit"></i></button>
  </a>
  <a href="{% url 'blog:post_delete' id=post.id %}" id="delete">
    <button type="button" class="btn btn-danger">Delete <i class="fas fa-trash-alt"></i></button>
  </a>
</div>
{% endif %}
<br><br>
<hr>

{% if not post.restrict_comment %}
<div class="main-comment-section">
  {% include 'blog/comments.html' %}
</div>
{% endif %}

{% endblock %}